<a href="https://colab.research.google.com/github/StephanieRomao/DataTwitter-Eleitoral/blob/main/Etapa_2_Coleta_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Apresentação do projeto
#####Proposta para a construção de uma aplicação que realiza análise de sentimentos dos candidatos à presidência.

In [62]:
pip install snscrape

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: snscrape in /usr/local/lib/python3.7/dist-packages (0.3.4)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.7/dist-packages (from snscrape) (2.23.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from snscrape) (4.2.6)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from snscrape) (4.6.3)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (2022.6.15)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (3.0.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (1.7.1)

#Importando as bibliotecas

In [63]:
import snscrape.modules.twitter as sntwitter

#Manipulação de dados
import pandas as pd

In [64]:
maximo_de_tweets = 10000

#Lula

In [65]:
lista_de_twitts_lula = []

In [66]:
type (lista_de_twitts_lula)

list

In [67]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper ( ['lula'] ).get_items ()):
  if i > maximo_de_tweets:
    break
  lista_de_twitts_lula.append ([tweet.date, tweet.id, tweet.content])

In [68]:
dataframe_tweets_lula = pd.DataFrame(lista_de_twitts_lula, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [69]:
dataframe_tweets_lula.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 17:18:47+00:00,1553429912534532098,Uma das grandes diferenças entre Voldemort e L...
1,2022-07-30 17:18:46+00:00,1553429910727053312,Lula simplesmente lotou o Centro de Eventos da...
2,2022-07-30 17:18:46+00:00,1553429910579970048,@senadorhumberto @LulaOficial Por onde passam ...
3,2022-07-30 17:18:46+00:00,1553429910454259713,@LulaOficial https://t.co/8aOaRoT0YM
4,2022-07-30 17:18:45+00:00,1553429906578604042,@MarceloUchoa_ Impressionate a quantidade de p...

In [70]:
dataframe_tweets_lula['Cadidato'] = 'Lula'

In [71]:
dataframe_tweets_lula.head()

,Data_Hora,IdTweet,Tweet,Cadidato
0,2022-07-30 17:18:47+00:00,1553429912534532098,Uma das grandes diferenças entre Voldemort e L...,Lula
1,2022-07-30 17:18:46+00:00,1553429910727053312,Lula simplesmente lotou o Centro de Eventos da...,Lula
2,2022-07-30 17:18:46+00:00,1553429910579970048,@senadorhumberto @LulaOficial Por onde passam ...,Lula
3,2022-07-30 17:18:46+00:00,1553429910454259713,@LulaOficial https://t.co/8aOaRoT0YM,Lula
4,2022-07-30 17:18:45+00:00,1553429906578604042,@MarceloUchoa_ Impressionate a quantidade de p...,Lula

#Jair Bolsonaro

In [72]:
lista_de_twitts_jair_bolsonaro = []

In [73]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper ( ['jair bolsonaro'] ).get_items ()):
  if i > maximo_de_tweets:
    break
  lista_de_twitts_jair_bolsonaro.append ([tweet.date, tweet.id, tweet.content])

In [74]:
dataframe_tweets_jair_bolsonaro = pd.DataFrame(lista_de_twitts_jair_bolsonaro, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [75]:
dataframe_tweets_jair_bolsonaro.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 17:21:26+00:00,1553430579437248519,Tem q ser macho 3 vezes para cassar o Registro...
1,2022-07-30 17:21:25+00:00,1553430574873862144,Não tem jeito. É @jairbolsonaro no primeiro tu...
2,2022-07-30 17:21:23+00:00,1553430567550599168,@jairbolsonaro Vai ser no 1 turno 🇧🇷🇧🇷🇧🇷\nÉ 22.
3,2022-07-30 17:21:22+00:00,1553430563377258499,"@Metropoles @jairbolsonaro , o q aconteceu q o..."
4,2022-07-30 17:21:18+00:00,1553430546897928194,@jairbolsonaro Qquer presidente com o compromi...

In [76]:
dataframe_tweets_jair_bolsonaro['Cadidato'] = 'Bolsonaro'

In [77]:
dataframe_tweets_jair_bolsonaro.head()

,Data_Hora,IdTweet,Tweet,Cadidato
0,2022-07-30 17:21:26+00:00,1553430579437248519,Tem q ser macho 3 vezes para cassar o Registro...,Bolsonaro
1,2022-07-30 17:21:25+00:00,1553430574873862144,Não tem jeito. É @jairbolsonaro no primeiro tu...,Bolsonaro
2,2022-07-30 17:21:23+00:00,1553430567550599168,@jairbolsonaro Vai ser no 1 turno 🇧🇷🇧🇷🇧🇷\nÉ 22.,Bolsonaro
3,2022-07-30 17:21:22+00:00,1553430563377258499,"@Metropoles @jairbolsonaro , o q aconteceu q o...",Bolsonaro
4,2022-07-30 17:21:18+00:00,1553430546897928194,@jairbolsonaro Qquer presidente com o compromi...,Bolsonaro

#Ciro Gomes

In [78]:
lista_de_twitts_ciro_gomes = []

In [79]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper ( ['ciro gomes'] ).get_items ()):
  if i > maximo_de_tweets:
    break
  lista_de_twitts_ciro_gomes.append ([tweet.date, tweet.id, tweet.content])

In [80]:
dataframe_tweets_ciro_gomes = pd.DataFrame(lista_de_twitts_ciro_gomes, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [81]:
dataframe_tweets_ciro_gomes.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 17:24:05+00:00,1553431248596500481,@RonnyCombate @cirogomes https://t.co/isKINwEm3p
1,2022-07-30 17:24:05+00:00,1553431247761940480,@MarleneLouren11 @andersongontijo @Alfenoide @...
2,2022-07-30 17:24:02+00:00,1553431235518676992,"@cirogomes Vira o disco, é Lula é PT já deu Ciru."
3,2022-07-30 17:24:01+00:00,1553431229827088389,@cirogomes Acho que não teria não.
4,2022-07-30 17:24:00+00:00,1553431225787944962,@leiaflaviano @cirogomes Parece a convenção do...

In [82]:
dataframe_tweets_ciro_gomes['Cadidato'] = 'Ciro'

In [83]:
dataframe_tweets_ciro_gomes.head()

,Data_Hora,IdTweet,Tweet,Cadidato
0,2022-07-30 17:24:05+00:00,1553431248596500481,@RonnyCombate @cirogomes https://t.co/isKINwEm3p,Ciro
1,2022-07-30 17:24:05+00:00,1553431247761940480,@MarleneLouren11 @andersongontijo @Alfenoide @...,Ciro
2,2022-07-30 17:24:02+00:00,1553431235518676992,"@cirogomes Vira o disco, é Lula é PT já deu Ciru.",Ciro
3,2022-07-30 17:24:01+00:00,1553431229827088389,@cirogomes Acho que não teria não.,Ciro
4,2022-07-30 17:24:00+00:00,1553431225787944962,@leiaflaviano @cirogomes Parece a convenção do...,Ciro

#Simone Tebet

In [84]:
lista_de_twitts_simone_tebet = []

In [85]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper ( ['simone tebet'] ).get_items ()):
  if i > maximo_de_tweets:
    break
  lista_de_twitts_simone_tebet.append ([tweet.date, tweet.id, tweet.content])

In [86]:
dataframe_tweets_simone_tebet = pd.DataFrame(lista_de_twitts_simone_tebet, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [87]:
dataframe_tweets_simone_tebet.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 17:22:51+00:00,1553430938343936004,"@panga2021 Calma, Simone Tebet pode ser uma su..."
1,2022-07-30 17:20:46+00:00,1553430411182751745,@Dilbruniera3 @WDordet @PSDBoficial @PatrciaPa...
2,2022-07-30 17:20:44+00:00,1553430405919002624,@BolivarianaRede @wanderleyyp @parox40 @simone...
3,2022-07-30 17:20:04+00:00,1553430238218096641,@simonetebetbr aposto que vai subir no palanqu...
4,2022-07-30 17:20:01+00:00,1553430225786126337,@freire_roberto Que cara chato ainda bem que @...

In [88]:
dataframe_tweets_simone_tebet['Cadidato'] = 'Simone'

In [89]:
dataframe_tweets_simone_tebet.head()

,Data_Hora,IdTweet,Tweet,Cadidato
0,2022-07-30 17:22:51+00:00,1553430938343936004,"@panga2021 Calma, Simone Tebet pode ser uma su...",Simone
1,2022-07-30 17:20:46+00:00,1553430411182751745,@Dilbruniera3 @WDordet @PSDBoficial @PatrciaPa...,Simone
2,2022-07-30 17:20:44+00:00,1553430405919002624,@BolivarianaRede @wanderleyyp @parox40 @simone...,Simone
3,2022-07-30 17:20:04+00:00,1553430238218096641,@simonetebetbr aposto que vai subir no palanqu...,Simone
4,2022-07-30 17:20:01+00:00,1553430225786126337,@freire_roberto Que cara chato ainda bem que @...,Simone

#André Janones

In [90]:
lista_de_twitts_andre_janones = []

In [91]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper ( ['andré janones'] ).get_items ()):
  if i > maximo_de_tweets:
    break
  lista_de_twitts_andre_janones.append ([tweet.date, tweet.id, tweet.content])

In [92]:
dataframe_tweets_andre_janones = pd.DataFrame(lista_de_twitts_andre_janones, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [93]:
dataframe_tweets_andre_janones.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 17:28:54+00:00,1553432460570120193,"Sou feio, isso é um fato. Mas meu medo de faze..."
1,2022-07-30 17:24:40+00:00,1553431392733863937,@cassitinha34 @de_mansu @leilatagusagawa @Andr...
2,2022-07-30 17:22:32+00:00,1553430859826532355,André Janones decidiu apoiar Lula já no primei...
3,2022-07-30 17:15:30+00:00,1553429086327939073,"Hoje na convenção do meu partido em SP, frisei..."
4,2022-07-30 17:15:10+00:00,1553429003159101440,André Janones mostrou a sua cara o cara que er...

In [94]:
dataframe_tweets_andre_janones['Cadidato'] = 'André'

In [95]:
dataframe_tweets_andre_janones.head()

,Data_Hora,IdTweet,Tweet,Cadidato
0,2022-07-30 17:28:54+00:00,1553432460570120193,"Sou feio, isso é um fato. Mas meu medo de faze...",André
1,2022-07-30 17:24:40+00:00,1553431392733863937,@cassitinha34 @de_mansu @leilatagusagawa @Andr...,André
2,2022-07-30 17:22:32+00:00,1553430859826532355,André Janones decidiu apoiar Lula já no primei...,André
3,2022-07-30 17:15:30+00:00,1553429086327939073,"Hoje na convenção do meu partido em SP, frisei...",André
4,2022-07-30 17:15:10+00:00,1553429003159101440,André Janones mostrou a sua cara o cara que er...,André

#Leonardo Péricles

In [96]:
lista_de_twitts_leonardo_pericles = []

In [97]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper ( ['leonardo péricles'] ).get_items ()):
  if i > maximo_de_tweets:
    break
  lista_de_twitts_leonardo_pericles.append ([tweet.date, tweet.id, tweet.content])

In [98]:
dataframe_tweets_leonardo_pericles = pd.DataFrame(lista_de_twitts_leonardo_pericles, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [99]:
dataframe_tweets_leonardo_pericles.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 16:38:16+00:00,1553419716831727616,☆☆☆●●●ATENÇÃO TODOS NEGROS E NEGRAS DO BRASIL ...
1,2022-07-30 16:17:32+00:00,1553414501155962882,@AdenorLeonardo @RicardoVale01 Vou no Leonardo...
2,2022-07-30 09:07:57+00:00,1553306390495727617,#LeonardoPericles
3,2022-07-30 02:56:13+00:00,1553212842635059200,"#BolsonaroNaCadeia, Ciro, Simone, Bivar, Janon..."
4,2022-07-30 02:33:50+00:00,1553207211161227264,@ThiagoResiste #LeonardoPericles

In [100]:
dataframe_tweets_leonardo_pericles['Cadidato'] = 'Péricles'

In [101]:
dataframe_tweets_leonardo_pericles.head()

,Data_Hora,IdTweet,Tweet,Cadidato
0,2022-07-30 16:38:16+00:00,1553419716831727616,☆☆☆●●●ATENÇÃO TODOS NEGROS E NEGRAS DO BRASIL ...,Péricles
1,2022-07-30 16:17:32+00:00,1553414501155962882,@AdenorLeonardo @RicardoVale01 Vou no Leonardo...,Péricles
2,2022-07-30 09:07:57+00:00,1553306390495727617,#LeonardoPericles,Péricles
3,2022-07-30 02:56:13+00:00,1553212842635059200,"#BolsonaroNaCadeia, Ciro, Simone, Bivar, Janon...",Péricles
4,2022-07-30 02:33:50+00:00,1553207211161227264,@ThiagoResiste #LeonardoPericles,Péricles

#Concatenação das listas acima

In [102]:
dataframe_final = pd.concat([dataframe_tweets_lula, dataframe_tweets_jair_bolsonaro, dataframe_tweets_ciro_gomes, dataframe_tweets_simone_tebet, dataframe_tweets_leonardo_pericles, dataframe_tweets_andre_janones], axis=0)

In [103]:
dataframe_final.head()

,Data_Hora,IdTweet,Tweet,Cadidato
0,2022-07-30 17:18:47+00:00,1553429912534532098,Uma das grandes diferenças entre Voldemort e L...,Lula
1,2022-07-30 17:18:46+00:00,1553429910727053312,Lula simplesmente lotou o Centro de Eventos da...,Lula
2,2022-07-30 17:18:46+00:00,1553429910579970048,@senadorhumberto @LulaOficial Por onde passam ...,Lula
3,2022-07-30 17:18:46+00:00,1553429910454259713,@LulaOficial https://t.co/8aOaRoT0YM,Lula
4,2022-07-30 17:18:45+00:00,1553429906578604042,@MarceloUchoa_ Impressionate a quantidade de p...,Lula

In [104]:
dataframe_final['Cadidato'].unique()

array(['Lula', 'Bolsonaro', 'Ciro', 'Simone', 'Péricles', 'André'],
      dtype=object)

#Salvando o arquivo em CSV para utilizar na próxima etapa
####Isso ajuda a conectar cada uma das etapas sem ter um único arquivo gigante do qual posso me perder com facilidade.

In [105]:
dataframe_final.to_csv ('dataframe_final_candidatos.csv', sep= ',', index=False)