<a href="https://colab.research.google.com/github/StephanieRomao/DataTwitter-Eleitoral/blob/main/Etapa_2_Coleta_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Apresentação do projeto
#####Proposta para a construção de uma aplicação que realiza análise de sentimentos dos candidatos à presidência.

In [11]:
pip install snscrape

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: snscrape in /usr/local/lib/python3.7/dist-packages (0.3.4)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.7/dist-packages (from snscrape) (2.23.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from snscrape) (4.6.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from snscrape) (4.2.6)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (2022.6.15)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (3.0.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (1.7.1)

#Importando as bibliotecas

In [54]:
import snscrape.modules.twitter as sntwitter

#Manipulação de dados
import pandas as pd

In [13]:
maximo_de_tweets = 10

#Lula

In [25]:
lista_de_twitts_lula = []

In [26]:
type (lista_de_twitts_lula)

list

In [27]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper ( ['lula'] ).get_items ()):
  if i > maximo_de_tweets:
    break
  lista_de_twitts_lula.append ([tweet.date, tweet.id, tweet.content])

In [28]:
dataframe_tweets_lula = pd.DataFrame(lista_de_twitts_lula, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [29]:
dataframe_tweets_lula.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 14:55:05+00:00,1553393749631303681,@vidaloukanomar @liziara @YaiaSobreira @alvaro...
1,2022-07-30 14:55:04+00:00,1553393747936923649,"Quem for votar no Lula, me segue que eu sigo d..."
2,2022-07-30 14:55:04+00:00,1553393746657656833,@FABIOAGUAYO @SF_Moro @rosangelamorosp E vão p...
3,2022-07-30 14:55:04+00:00,1553393746334588928,@LulaOficial Bom dia presidente Lula
4,2022-07-30 14:55:04+00:00,1553393745655103490,@abdalafarah @LulaOficial Eu já tenho mais de ...

In [30]:
dataframe_tweets_lula['Cadidato'] = 'Lula'

In [31]:
dataframe_tweets_lula.head()

,Data_Hora,IdTweet,Tweet,Cadidato
0,2022-07-30 14:55:05+00:00,1553393749631303681,@vidaloukanomar @liziara @YaiaSobreira @alvaro...,Lula
1,2022-07-30 14:55:04+00:00,1553393747936923649,"Quem for votar no Lula, me segue que eu sigo d...",Lula
2,2022-07-30 14:55:04+00:00,1553393746657656833,@FABIOAGUAYO @SF_Moro @rosangelamorosp E vão p...,Lula
3,2022-07-30 14:55:04+00:00,1553393746334588928,@LulaOficial Bom dia presidente Lula,Lula
4,2022-07-30 14:55:04+00:00,1553393745655103490,@abdalafarah @LulaOficial Eu já tenho mais de ...,Lula

#Jair Bolsonaro

In [19]:
lista_de_twitts_jair_bolsonaro = []

In [20]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper ( ['jair bolsonaro'] ).get_items ()):
  if i > maximo_de_tweets:
    break
  lista_de_twitts_jair_bolsonaro.append ([tweet.date, tweet.id, tweet.content])

In [21]:
dataframe_tweets_jair_bolsonaro = pd.DataFrame(lista_de_twitts_jair_bolsonaro, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [22]:
dataframe_tweets_jair_bolsonaro.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 14:54:07+00:00,1553393506504392706,@CarlaZambelli38 @jairbolsonaro Bom dia Carla
1,2022-07-30 14:54:06+00:00,1553393504319160320,@jairbolsonaro grande feito https://t.co/7WpPH...
2,2022-07-30 14:54:06+00:00,1553393503543169024,@jairbolsonaro Avante Brasil!
3,2022-07-30 14:54:01+00:00,1553393481577631745,@LulaOficial Esse aí que escreve os twitter do...
4,2022-07-30 14:54:00+00:00,1553393476934373377,@cris_tivolitom @Gliceriaroratt2 Gasolina subi...

In [23]:
dataframe_tweets_jair_bolsonaro['Cadidato'] = 'Bolsonaro'

In [24]:
dataframe_tweets_jair_bolsonaro.head()

,Data_Hora,IdTweet,Tweet,Cadidato
0,2022-07-30 14:54:07+00:00,1553393506504392706,@CarlaZambelli38 @jairbolsonaro Bom dia Carla,Bolsonaro
1,2022-07-30 14:54:06+00:00,1553393504319160320,@jairbolsonaro grande feito https://t.co/7WpPH...,Bolsonaro
2,2022-07-30 14:54:06+00:00,1553393503543169024,@jairbolsonaro Avante Brasil!,Bolsonaro
3,2022-07-30 14:54:01+00:00,1553393481577631745,@LulaOficial Esse aí que escreve os twitter do...,Bolsonaro
4,2022-07-30 14:54:00+00:00,1553393476934373377,@cris_tivolitom @Gliceriaroratt2 Gasolina subi...,Bolsonaro

#Ciro Gomes

In [33]:
lista_de_twitts_ciro_gomes = []

In [34]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper ( ['ciro gomes'] ).get_items ()):
  if i > maximo_de_tweets:
    break
  lista_de_twitts_ciro_gomes.append ([tweet.date, tweet.id, tweet.content])

In [35]:
dataframe_tweets_ciro_gomes = pd.DataFrame(lista_de_twitts_ciro_gomes, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [36]:
dataframe_tweets_ciro_gomes.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 14:56:14+00:00,1553394039575220231,"Isolado, Ciro elogia Lula e sinaliza que esta ..."
1,2022-07-30 14:56:06+00:00,1553394005332877313,@o_antagonista @cirogomes É UMA PENA \nO BRASI...
2,2022-07-30 14:56:06+00:00,1553394004628226048,@ofilhodopastor @AndreJanonesAdv @cirogomes Ma...
3,2022-07-30 14:56:01+00:00,1553393985921716226,@Lueira2 @UOLNoticias @cirogomes Mas ele não q...
4,2022-07-30 14:55:57+00:00,1553393968678948864,@AndreJanonesAdv @cirogomes É assim que funcio...

In [37]:
dataframe_tweets_ciro_gomes['Cadidato'] = 'Ciro'

In [38]:
dataframe_tweets_ciro_gomes.head()

,Data_Hora,IdTweet,Tweet,Cadidato
0,2022-07-30 14:56:14+00:00,1553394039575220231,"Isolado, Ciro elogia Lula e sinaliza que esta ...",Ciro
1,2022-07-30 14:56:06+00:00,1553394005332877313,@o_antagonista @cirogomes É UMA PENA \nO BRASI...,Ciro
2,2022-07-30 14:56:06+00:00,1553394004628226048,@ofilhodopastor @AndreJanonesAdv @cirogomes Ma...,Ciro
3,2022-07-30 14:56:01+00:00,1553393985921716226,@Lueira2 @UOLNoticias @cirogomes Mas ele não q...,Ciro
4,2022-07-30 14:55:57+00:00,1553393968678948864,@AndreJanonesAdv @cirogomes É assim que funcio...,Ciro

#Simone Tebet

In [14]:
lista_de_twitts_simone_tebet = []

In [16]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper ( ['simone tebet'] ).get_items ()):
  if i > maximo_de_tweets:
    break
  lista_de_twitts_simone_tebet.append ([tweet.date, tweet.id, tweet.content])

In [17]:
dataframe_tweets_simone_tebet = pd.DataFrame(lista_de_twitts_simone_tebet, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [18]:
dataframe_tweets_simone_tebet.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 14:51:10+00:00,1553392764175400961,"@simonetebetbr BOM DIA TABLET, MEUS VIZINHOS Q..."
1,2022-07-30 14:50:04+00:00,1553392489700233219,@simonetebetbr no PÂNICO 😱 entrou em PÂNICO 😱 ...
2,2022-07-30 14:49:29+00:00,1553392340273975298,"No Pânico, Simone Tebet ataca Bolsonaro e diz ..."
3,2022-07-30 14:48:37+00:00,1553392122954391553,@meupaiseursal @cirogomes @simonetebetbr Conco...
4,2022-07-30 14:47:20+00:00,1553391800634654720,@GraziMFrauches @simonetebetbr Já tive uma cer...

In [39]:
dataframe_tweets_simone_tebet['Cadidato'] = 'Simone'

In [40]:
dataframe_tweets_simone_tebet.head()

,Data_Hora,IdTweet,Tweet,Cadidato
0,2022-07-30 14:51:10+00:00,1553392764175400961,"@simonetebetbr BOM DIA TABLET, MEUS VIZINHOS Q...",Simone
1,2022-07-30 14:50:04+00:00,1553392489700233219,@simonetebetbr no PÂNICO 😱 entrou em PÂNICO 😱 ...,Simone
2,2022-07-30 14:49:29+00:00,1553392340273975298,"No Pânico, Simone Tebet ataca Bolsonaro e diz ...",Simone
3,2022-07-30 14:48:37+00:00,1553392122954391553,@meupaiseursal @cirogomes @simonetebetbr Conco...,Simone
4,2022-07-30 14:47:20+00:00,1553391800634654720,@GraziMFrauches @simonetebetbr Já tive uma cer...,Simone

#André Janones

In [41]:
lista_de_twitts_andre_janones = []

In [42]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper ( ['andré janones'] ).get_items ()):
  if i > maximo_de_tweets:
    break
  lista_de_twitts_andre_janones.append ([tweet.date, tweet.id, tweet.content])

In [43]:
dataframe_tweets_andre_janones = pd.DataFrame(lista_de_twitts_andre_janones, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [44]:
dataframe_tweets_andre_janones.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 14:58:17+00:00,1553394554245611521,"""Lula está fazendo um arrastão"", diz \n Helena..."
1,2022-07-30 14:52:18+00:00,1553393051447476225,Democracia Política e novo Reformismo: Pablo O...
2,2022-07-30 14:51:22+00:00,1553392814909784064,@AndreJanonesAdv @LulaOficial Vai lá André Jan...
3,2022-07-30 14:49:22+00:00,1553392312616632321,observação importante: Nelson se elegeu pelo A...
4,2022-07-30 14:48:01+00:00,1553391972160782337,@AndreJanonesAdv O mais legal é que o novo Jea...

In [45]:
dataframe_tweets_andre_janones['Cadidato'] = 'André'

In [47]:
dataframe_tweets_andre_janones.head()

,Data_Hora,IdTweet,Tweet,Cadidato
0,2022-07-30 14:58:17+00:00,1553394554245611521,"""Lula está fazendo um arrastão"", diz \n Helena...",André
1,2022-07-30 14:52:18+00:00,1553393051447476225,Democracia Política e novo Reformismo: Pablo O...,André
2,2022-07-30 14:51:22+00:00,1553392814909784064,@AndreJanonesAdv @LulaOficial Vai lá André Jan...,André
3,2022-07-30 14:49:22+00:00,1553392312616632321,observação importante: Nelson se elegeu pelo A...,André
4,2022-07-30 14:48:01+00:00,1553391972160782337,@AndreJanonesAdv O mais legal é que o novo Jea...,André

#Leonardo Péricles

In [48]:
lista_de_twitts_leonardo_pericles = []

In [49]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper ( ['leonardo péricles'] ).get_items ()):
  if i > maximo_de_tweets:
    break
  lista_de_twitts_leonardo_pericles.append ([tweet.date, tweet.id, tweet.content])

In [50]:
dataframe_tweets_leonardo_pericles = pd.DataFrame(lista_de_twitts_leonardo_pericles, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [51]:
dataframe_tweets_leonardo_pericles.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 09:07:57+00:00,1553306390495727617,#LeonardoPericles
1,2022-07-30 02:56:13+00:00,1553212842635059200,"#BolsonaroNaCadeia, Ciro, Simone, Bivar, Janon..."
2,2022-07-30 02:33:50+00:00,1553207211161227264,@ThiagoResiste #LeonardoPericles
3,2022-07-30 01:12:28+00:00,1553186730655862784,☆☆☆●●●ATENÇÃO TODOS NEGROS E NEGRAS DO BRASIL ...
4,2022-07-30 00:40:01+00:00,1553178565105094659,&gt;&gt;&gt;*** *** ALGUMA REDE DE TELEVISÃO ...

In [52]:
dataframe_tweets_leonardo_pericles['Cadidato'] = 'Péricles'

In [53]:
dataframe_tweets_leonardo_pericles.head()

,Data_Hora,IdTweet,Tweet,Cadidato
0,2022-07-30 09:07:57+00:00,1553306390495727617,#LeonardoPericles,Péricles
1,2022-07-30 02:56:13+00:00,1553212842635059200,"#BolsonaroNaCadeia, Ciro, Simone, Bivar, Janon...",Péricles
2,2022-07-30 02:33:50+00:00,1553207211161227264,@ThiagoResiste #LeonardoPericles,Péricles
3,2022-07-30 01:12:28+00:00,1553186730655862784,☆☆☆●●●ATENÇÃO TODOS NEGROS E NEGRAS DO BRASIL ...,Péricles
4,2022-07-30 00:40:01+00:00,1553178565105094659,&gt;&gt;&gt;*** *** ALGUMA REDE DE TELEVISÃO ...,Péricles